[package]
name = "weekend-ray-tracing"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17.11"
itertools = "0.14.0"
rayon = "1.10.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "bench"
harness = false
